[package]
name = "raptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log  = "0.4"
primes = "0.3.0"

[dev-dependencies]
env_logger = "0.10.0"
rand = "0.8"
